specVersion: 0.2.0
name: wormhole-darwinia
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: wss://rpc.darwinia.network/
  dictionary: https://api.subquery.network/sq/itering/darwinia-dictionary
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 6358000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
