specVersion: 1.0.0
name: darwinia
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: "*"
  query:
    name: '@subql/query'
    version: "*"
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x729cb8f2cf428adcf81fe69610edda32c5711b2ff17de747e8604a3587021db8'
  endpoint: wss://rpc.darwinia.network/
  dictionary: https://api.subquery.network/sq/darwinia-network/darwinia-dictionary
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 10440380
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabBacking
            method: TokenLocked
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabBacking
            method: TokenLockedConfirmed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabBacking
            method: TokenUnlocked
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabDispatch
            method: MessageVersionSpecMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabDispatch
            method: MessageDispatched
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: kton
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed
