specVersion: 0.2.0
name: helix-shiden
version: 1.0.0
description: ''
repository: git@github.com:helix-bridge/indexer.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
  endpoint: wss://shiden-rpc.dwellir.com
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 2332034
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
            method: Success

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
            method: XcmpMessageSent

