specVersion: 1.0.0
name: crab
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: v1.14.1
  query:
    name: '@subql/query'
    version: v1.7.0
description: ''
repository: git@github.com:helix-bridge/indexer.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x86e49c195aeae7c5c4a86ced251f1a28c67b3c35d8289c387ede1776cdd88b24'
  endpoint: wss://crab-rpc.darwinia.network
dataSources:
  - kind: substrate/Runtime
    startBlock: 339891
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageVersionSpecMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageWeightMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageCallValidateFailed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageDispatched
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
            method: Success
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
            method: Fail
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: xcmpQueue
            method: XcmpMessageSent
