specVersion: 0.2.0
name: wormhole-pangoro
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0xf37f31c4481e3c937ad40b672c561d0c0b1fb70b40e51a0d56dad30d60e4db58'
  endpoint: wss://pangoro-rpc.darwinia.network/
  dictionary: https://api.subquery.network/sq/darwinia-network/pangoro-dictionary
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 26960
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: substrate2SubstrateBacking
            method: TokenLocked

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: substrate2SubstrateBacking
            method: TokenLockedConfirmed

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: substrate2SubstrateBacking
            method: TokenUnlocked
            
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinDispatch
            method: MessageVersionSpecMismatch
 
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer # ring: mainnet -> dvm

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: kton
            method: Transfer # kton: mainnet -> dvm

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Endowed # ring: dvm -> mainnet

        # - handler: handleEvent
        #   kind: substrate/EventHandler
        #   filter:
        #     module: balances
        #     method: Transfer