specVersion: 0.2.0
name: wormhole-pangolin
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0xce44bd16fc276f9e457b452577b6c2678e57768260012af127479fed806da7e7'
  endpoint: wss://pangolin-rpc.darwinia.network
  dictionary: https://api.subquery.network/sq/darwinia-network/pangolin-dictionary 
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 119850
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageVersionSpecMismatch 
       
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer # ring: mainnet -> dvm

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: kton
            method: Transfer # kton: mainnet -> dvm

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: DVMTransfer # ring: dvm -> mainnet

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: KtonDVMTransfer # kton dvm -> mainnet

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: Executed

 