specVersion: 0.2.0
name: wormhole-pangolin
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x46720335bb0a5c81a29777a9ad81afcda36b70f34103ebea42fb55332a1b79b4'
  endpoint: wss://pangolin-rpc.darwinia.network
  dictionary: https://api.subquery.network/sq/darwinia-network/pangolin-dictionary 
  chaintypes:
    file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 200000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageVersionSpecMismatch 
       
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageWeightMismatch

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangoroDispatch
            method: MessageCallValidateFailed

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinParachainDispatch
            method: MessageVersionSpecMismatch 
       
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinParachainDispatch
            method: MessageWeightMismatch

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinParachainDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgePangolinParachainDispatch
            method: MessageCallValidateFailed

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: DVMTransfer

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: kton
            method: Transfer

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toPangolinParachainBacking
            method: TokenLocked

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toPangolinParachainBacking
            method: TokenLockedConfirmed
 
