version: '3'

services:
  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  subquery-node:
    image: onfinality/subql-node:v1.14.1
    depends_on:
      'postgres':
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    volumes:
      - ./:/app
    command:
      - --disable-historical=true
      - -f=ipfs://QmNRfPN1Tjh6mGag6saECsfQppvTjXm8YHy9zMdbiBC5Fw
      - --db-schema=app
      - --network-endpoint=wss://wss.api.moonriver.moonbeam.network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://subquery-node:3000/ready']
      interval: 3s
      timeout: 5s
      retries: 10

  graphql-engine:
    image: onfinality/subql-query:v1.7.0
    ports:
      - 3000:3000
    depends_on:
      'postgres':
        condition: service_healthy
      'subquery-node':
        condition: service_healthy
    restart: always
    environment:
      DB_USER: postgres
      DB_PASS: postgres
      DB_DATABASE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
    command:
      - --name=app
      - --playground
      - --indexer=http://subquery-node:3000
