specVersion: 0.2.0
name: wormhole-crab
version: 1.0.0
description: ''
repository: git@github.com:darwinia-network/subql-wormhole.git

schema:
  file: ./schema.graphql

network:
  genesisHash: '0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65'
  endpoint: wss://darwinia-crab.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/darwinia-network/crab-dictionary
  chaintypes:
      file: ./types.yaml

dataSources:
  - kind: substrate/Runtime
    startBlock: 10348480 # keep the same as dictionary
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageVersionSpecMismatch 

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageWeightMismatch 
       
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageVersionSpecMismatch 

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageWeightMismatch 
       
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageDispatched

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: DVMTransfer

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabParachainBacking
            method: TokenLocked

        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabParachainBacking
            method: TokenLockedConfirmed

