specVersion: 1.0.0
name: crab
version: 0.0.1
runner:
  node:
    name: '@subql/node'
    version: v1.14.1
  query:
    name: '@subql/query'
    version: v1.7.0
description: ''
repository: git@github.com:helix-bridge/indexer.git
schema:
  file: ./schema.graphql
network:
  chainId: '0x34f61bfda344b3fad3c3e38832a91448b3c613b199eb23e5110a635d71c13c65'
  endpoint: wss://crab-rpc.darwinia.network
  dictionary: https://api.subquery.network/sq/darwinia-network/crab-dictionary
  chaintypes:
    file: ./types.yaml
dataSources:
  - kind: substrate/Runtime
    startBlock: 12000000
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageVersionSpecMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageWeightMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageCallValidateFailed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeDarwiniaDispatch
            method: MessageDispatched
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageVersionSpecMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageWeightMismatch
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageCallValidateFailed
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: bridgeCrabParachainDispatch
            method: MessageDispatched
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: ethereum
            method: DVMTransfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: kton
            method: Transfer
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabParachainBacking
            method: TokenLocked
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: toCrabParachainBacking
            method: TokenLockedConfirmed
