name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:


env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  publish-indexer:
    name: Publish indexer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.DOCKER_REGISTRY }}

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 7

      - uses: olegtarasov/get-tag@v2.1
        id: tag-name

      - name: Build apollo with sha
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: apollo/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/apollo:sha-${{ steps.short-sha.outputs.sha }}

      - name: Build apollo with tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          context: .
          file: apollo/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/apollo:${{ steps.tag-name.outputs.tag }}

      - name: Build ponder with sha
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ponder/lnv3/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:sha-${{ steps.short-sha.outputs.sha }}

      - name: Build ponder with tag
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          push: true
          file: ponder/lnv3/Dockerfile
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/ponder:${{ steps.tag-name.outputs.tag }}


